### ISSUE TITLE
Make this image available as a GitHub Action

### ISSUE THREAD

**Issue by Guerric-P** [SAP/devops-docker-mta-archive-builder#25]
It would be very useful to add a `action.yml` file with the required inputs, in order to use it as an Action

**Comment by fwilhe** [comment]
Hi @Guerric-P 

thanks for your suggestion, but I need to inform you that this image and the java-based build tool it uses are not maintained anymore. The new go-based tool is [here](https://github.com/SAP/cloud-mta-build-tool), they also maintain a Docker image over there.

But we might already have something that suits your needs: [Project "piper" action](https://github.com/SAP/project-piper-action) is a GitHub Action that can make use of this image via the [`mtaBuild`](https://sap.github.io/jenkins-library/steps/mtaBuild/) step.

A usage example that installs the Cloud MTA Build tool and runs `mtaBuild` would be

```yaml
      - run: curl -L "https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.15/cloud-mta-build-tool_1.0.15_Linux_amd64.tar.gz" | sudo tar -zx -C /usr/local/bin

      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
          flags: "--installArtifacts"
          piper-version: master

```

I hope this helps.

Best,

Florian
